## DATA EXPLORATION

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')   

pd.set_option('display.max_columns', None)

In [ ]:

file_path = '../Data/raw_data.csv'

df = pd.read_csv(file_path, low_memory=False)

print(f"Dataset loaded: {len(df):,} rows x {len(df.columns)} columns")
print(f"Memory: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

Dataset loaded: 500,016 rows x 22 columns
Memory: 341.73 MB

In [5]:
# Column info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500016 entries, 0 to 500015
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    500016 non-null  int64
 1   Case Number           500016 non-null  object
 2   Date                  500016 non-null  object
 3   Block                 500016 non-null  object
 4   IUCR                  500016 non-null  object
 5   Primary Type          500016 non-null  object
 6   Description           500016 non-null  object
 7   Location Description  497617 non-null  object
 8   Arrest                500016 non-null  bool
 9   Domestic              500016 non-null  bool
 10  Beat                  500016 non-null  int64
 11  District              500016 non-null  int64
 12  Ward                  500014 non-null  float64
 13  Community Area        500002 non-null  float64
 14  FBI Code              500016 non-null  object
 15  X Coordinate          496305 non-null  float64
 16  Y Coordinate          496305 non-null  float64
 17  Year                  500016 non-null  int64
 18  Updated On            500016 non-null  object
 19  Latitude              496305 non-null  float64
 20  Longitude             496305 non-null  float64
 21  Location              496305 non-null  object
dtypes: bool(2), float64(6), int64(4), object(10)
memory usage: 77.3+ MB

In [6]:
# First few rows
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13812411,JJ226219,03/15/2025 10:00:00 AM,027XX S KOSTNER AVE,0820,THEFT,$500 AND UNDER,VEHICLE NON-COMMERCIAL,False,False,1031,10,22.0,30.0,06,1147501.0,1885494.0,2025,03/14/2026 03:41:39 PM,41.841752,-87.734216,"(41.841752071, -87.734215686)"
1,13776074,JJ182219,03/15/2025 10:00:00 AM,024XX W MONTROSE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1911,19,47.0,5.0,14,1158860.0,1929140.0,2025,03/14/2026 03:41:39 PM,41.961295,-87.691333,"(41.961295335, -87.691332906)"
2,13775931,JJ182192,03/15/2025 10:00:00 AM,062XX N WINTHROP AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,RESIDENCE,False,False,2433,24,48.0,77.0,24,1167725.0,1941624.0,2025,03/14/2026 03:41:39 PM,41.995365,-87.658379,"(41.995364897, -87.658378839)"
3,13775974,JJ182226,03/15/2025 10:00:00 AM,050XX S BLACKSTONE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,SCHOOL - PRIVATE GROUNDS,False,False,222,2,4.0,39.0,14,1186774.0,1871922.0,2025,03/14/2026 03:41:39 PM,41.803667,-87.590528,"(41.803667488, -87.590528166)"
4,13776897,JJ183396,03/15/2025 10:00:00 AM,105XX S CORLISS AVE,0810,THEFT,OVER $500,STREET,False,False,512,5,9.0,50.0,06,1183450.0,1835023.0,2025,03/14/2026 03:41:39 PM,41.702491,-87.603866,"(41.702490996, -87.603866153)"

In [7]:
# Missing values summary
missing = pd.DataFrame({
    'Column': df.columns,
    'Missing_Count': df.isnull().sum().values,
    'Missing_%': (df.isnull().sum().values / len(df) * 100).round(2)
})

missing = missing[missing['Missing_Count'] > 0].sort_values('Missing_%', ascending=False)
print(missing.to_string(index=False))

              Column  Missing_Count  Missing_%
        X Coordinate           3711       0.74
           Longitude           3711       0.74
            Latitude           3711       0.74
        Y Coordinate           3711       0.74
            Location           3711       0.74
Location Description           2399       0.48
      Community Area             14       0.00
                Ward              2       0.00

In [8]:
# Numerical columns summary
df.describe()

,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,5.000160e+05,500016.000000,500016.000000,500014.000000,500002.000000,4.963050e+05,4.963050e+05,500016.000000,496305.000000,496305.000000
mean,1.337971e+07,1157.454083,11.344981,23.170189,36.185037,1.165291e+06,1.887648e+06,2023.694586,41.847289,-87.668913
std,6.812624e+05,711.024994,7.105528,13.959284,21.601485,1.621758e+04,3.162769e+04,0.623371,0.086972,0.059050
min,2.742100e+04,111.000000,1.000000,1.000000,1.000000,1.091242e+06,1.813897e+06,2023.000000,41.644590,-87.939733
25%,1.322389e+07,533.000000,5.000000,10.000000,22.000000,1.153972e+06,1.860396e+06,2023.000000,41.772384,-87.710117
50%,1.340974e+07,1034.000000,10.000000,23.000000,32.000000,1.167108e+06,1.894156e+06,2024.000000,41.865275,-87.662038
75%,1.359444e+07,1732.000000,17.000000,34.000000,53.000000,1.176689e+06,1.910494e+06,2024.000000,41.910110,-87.627142
max,1.416586e+07,2535.000000,31.000000,50.000000,77.000000,1.205119e+06,1.951506e+06,2025.000000,42.022549,-87.524531

In [9]:
# Duplicate rows
duplicates = df.duplicated().sum()
print(f"Total duplicate rows: {duplicates:,}")
print(f"Percentage: {(duplicates/len(df)*100):.2f}%")

Total duplicate rows: 0
Percentage: 0.00%

In [10]:
# Check rows with missing coordinates
missing_coords = df[df['Latitude'].isnull()]

print(f"Rows missing coordinates: {len(missing_coords):,}")
print(f"\nSample of rows with missing coordinates:")
print(missing_coords[['Case Number', 'Date', 'Primary Type', 'Block', 'Latitude', 'Longitude']].head(10))

Rows missing coordinates: 3,711

Sample of rows with missing coordinates:
     Case Number                    Date        Primary Type  \
213     JK181984  03/15/2025 12:00:00 AM  DECEPTIVE PRACTICE
2032    JJ178364  03/12/2025 10:45:00 AM         SEX OFFENSE
2065    JJ178256  03/12/2025 09:15:00 AM     CRIMINAL DAMAGE
2068    JJ178242  03/12/2025 09:01:00 AM     CRIMINAL DAMAGE
2085    JJ178215  03/12/2025 08:30:00 AM             ASSAULT
2088    JJ178214  03/12/2025 08:25:00 AM   CRIMINAL TRESPASS
2089    JJ178192  03/12/2025 08:24:00 AM               THEFT
2090    JJ178182  03/12/2025 08:20:00 AM             ASSAULT
2107    JJ178171  03/12/2025 07:40:00 AM       OTHER OFFENSE
2108    JJ178187  03/12/2025 07:40:00 AM   CRIMINAL TRESPASS

                      Block  Latitude  Longitude
213       084XX S MORGAN ST       NaN        NaN
2032    024XX S WESTERN AVE       NaN        NaN
2065  013XX N CLEVELAND AVE       NaN        NaN
2068     073XX N ROGERS AVE       NaN        NaN
2085    029XX N ASHLAND AVE       NaN        NaN
2088      051XX W NORTH AVE       NaN        NaN
2089       074XX N CLARK ST       NaN        NaN
2090    012XX S WESTERN AVE       NaN        NaN
2107     057XX S HARLEM AVE       NaN        NaN
2108    019XX N WESTERN AVE       NaN        NaN

## DATA CLEANING

In [11]:
# Check if we should keep or remove these rows
print("Crime types with missing coordinates:")
print(missing_coords['Primary Type'].value_counts().head(10))

Crime types with missing coordinates:
Primary Type
DECEPTIVE PRACTICE            861
THEFT                         688
BATTERY                       451
OTHER OFFENSE                 299
CRIMINAL DAMAGE               250
ASSAULT                       231
MOTOR VEHICLE THEFT           180
NARCOTICS                     150
OFFENSE INVOLVING CHILDREN    109
CRIMINAL SEXUAL ASSAULT        90
Name: count, dtype: int64

In [12]:
# Save original count
original_count = len(df)

# Remove rows with missing coordinates
df_cleaned = df.dropna(subset=['Latitude', 'Longitude', 'X Coordinate', 'Y Coordinate', 'Location'])

removed = original_count - len(df_cleaned)
print(f"✓ Removed {removed:,} rows with missing coordinates")
print(f"✓ Remaining rows: {len(df_cleaned):,}")
print(f"✓ Retention rate: {(len(df_cleaned)/original_count*100):.2f}%")

✓ Removed 3,711 rows with missing coordinates
✓ Remaining rows: 496,305
✓ Retention rate: 99.26%

In [13]:
# Check missing location descriptions
missing_loc_desc = df_cleaned[df_cleaned['Location Description'].isnull()]
print(f"Rows with missing Location Description: {len(missing_loc_desc):,}")

# Fill with 'UNKNOWN'
df_cleaned['Location Description'] = df_cleaned['Location Description'].fillna('UNKNOWN')

print(f"\n✓ Filled missing Location Description with 'UNKNOWN'")

Rows with missing Location Description: 2,222

✓ Filled missing Location Description with 'UNKNOWN'

In [14]:
# Check remaining missing values
print("Missing Ward:", df_cleaned['Ward'].isnull().sum())
print("Missing Community Area:", df_cleaned['Community Area'].isnull().sum())

# These are very few - we can drop them or fill with mode
# Option: Drop rows with missing Ward/Community Area
df_cleaned = df_cleaned.dropna(subset=['Ward', 'Community Area'])

print(f"\n✓ Removed rows with missing Ward/Community Area")
print(f"✓ Final row count: {len(df_cleaned):,}")

Missing Ward: 2
Missing Community Area: 13

✓ Removed rows with missing Ward/Community Area
✓ Final row count: 496,290

In [15]:
# Convert Date column
df_cleaned['Date'] = pd.to_datetime(df_cleaned['Date'], format='%m/%d/%Y %I:%M:%S %p')

print("✓ Date column converted to datetime")
print(f"Date range: {df_cleaned['Date'].min()} to {df_cleaned['Date'].max()}")

✓ Date column converted to datetime
Date range: 2023-04-09 07:45:00 to 2025-03-15 10:00:00

In [16]:
# Convert Updated On column
df_cleaned['Updated On'] = pd.to_datetime(df_cleaned['Updated On'], format='%m/%d/%Y %I:%M:%S %p')

print("✓ Updated On column converted to datetime")

✓ Updated On column converted to datetime

In [17]:
# Extract useful date components
df_cleaned['Month'] = df_cleaned['Date'].dt.month
df_cleaned['Day'] = df_cleaned['Date'].dt.day
df_cleaned['Hour'] = df_cleaned['Date'].dt.hour
df_cleaned['DayOfWeek'] = df_cleaned['Date'].dt.dayofweek  # 0=Monday, 6=Sunday
df_cleaned['DayName'] = df_cleaned['Date'].dt.day_name()

print("✓ Extracted date features: Month, Day, Hour, DayOfWeek, DayName")
df_cleaned[['Date', 'Month', 'Day', 'Hour', 'DayOfWeek', 'DayName']].head()

✓ Extracted date features: Month, Day, Hour, DayOfWeek, DayName

                 Date  Month  Day  Hour  DayOfWeek   DayName
0 2025-03-15 10:00:00      3   15    10          5  Saturday
1 2025-03-15 10:00:00      3   15    10          5  Saturday
2 2025-03-15 10:00:00      3   15    10          5  Saturday
3 2025-03-15 10:00:00      3   15    10          5  Saturday
4 2025-03-15 10:00:00      3   15    10          5  Saturday

In [18]:
# Check updated data types
print("Updated Data Types:")
print(df_cleaned.dtypes)

Updated Data Types:
ID                               int64
Case Number                     object
Date                    datetime64[ns]
Block                           object
IUCR                            object
Primary Type                    object
Description                     object
Location Description            object
Arrest                            bool
Domestic                          bool
Beat                             int64
District                         int64
Ward                           float64
Community Area                 float64
FBI Code                        object
X Coordinate                   float64
Y Coordinate                   float64
Year                             int64
Updated On              datetime64[ns]
Latitude                       float64
Longitude                      float64
Location                        object
Month                            int32
Day                              int32
Hour                             int32
DayOfWeek                        int32
DayName                         object
dtype: object

In [19]:
# Verify no critical missing values remain
missing_check = df_cleaned.isnull().sum()
print("Remaining missing values:")
print(missing_check[missing_check > 0])

if missing_check.sum() == 0:
    print("\n✓ ✓ ✓ NO MISSING VALUES! Dataset is clean.")
else:
    print(f"\n⚠ Still have {missing_check.sum()} missing values to address")

Remaining missing values:
Series([], dtype: int64)

✓ ✓ ✓ NO MISSING VALUES! Dataset is clean.

In [20]:
print("="*60)
print("STEP 2 SUMMARY")
print("="*60)
print(f"Original dataset: {original_count:,} rows")
print(f"Cleaned dataset: {len(df_cleaned):,} rows")
print(f"Rows removed: {original_count - len(df_cleaned):,}")
print(f"Data retention: {(len(df_cleaned)/original_count*100):.2f}%")
print(f"\nNew features added: Month, Day, Hour, DayOfWeek, DayName")
print(f"Total columns: {len(df_cleaned.columns)}")

============================================================
STEP 2 SUMMARY
============================================================
Original dataset: 500,016 rows
Cleaned dataset: 496,290 rows
Rows removed: 3,726
Data retention: 99.25%

New features added: Month, Day, Hour, DayOfWeek, DayName
Total columns: 27

In [21]:
# Check current state of text columns
text_columns = ['Case Number', 'Block', 'IUCR', 'Primary Type', 'Description', 'Location Description', 'FBI Code']

print("Sample values before standardization:")
for col in text_columns[:3]:
    print(f"\n{col}:")
    print(df_cleaned[col].head(3).tolist())

Sample values before standardization:

Case Number:
['JJ226219', 'JJ182219', 'JJ182192']

Block:
['027XX S KOSTNER AVE', '024XX W MONTROSE AVE', '062XX N WINTHROP AVE']

IUCR:
['0820', '1310', '0470']

In [22]:
# Standardize: remove leading/trailing spaces and multiple spaces
for col in text_columns:
    df_cleaned[col] = df_cleaned[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

print("✓ Standardized text columns (removed extra spaces)")

✓ Standardized text columns (removed extra spaces)

In [23]:
# Primary Type - Crime categories
print("Unique Primary Types:", df_cleaned['Primary Type'].nunique())
print("\nTop 15 Crime Types:")
print(df_cleaned['Primary Type'].value_counts().head(15))

Unique Primary Types: 31

Top 15 Crime Types:
Primary Type
THEFT                         113837
BATTERY                        86813
CRIMINAL DAMAGE                55257
MOTOR VEHICLE THEFT            45845
ASSAULT                        44272
OTHER OFFENSE                  31881
DECEPTIVE PRACTICE             31168
ROBBERY                        18849
BURGLARY                       15340
WEAPONS VIOLATION              15283
NARCOTICS                      11481
CRIMINAL TRESPASS               9316
OFFENSE INVOLVING CHILDREN      3132
CRIMINAL SEXUAL ASSAULT         3092
SEX OFFENSE                     2469
Name: count, dtype: int64

In [24]:
# Location Description
print("Unique Location Descriptions:", df_cleaned['Location Description'].nunique())
print("\nTop 15 Locations:")
print(df_cleaned['Location Description'].value_counts().head(15))

Unique Location Descriptions: 140

Top 15 Locations:
Location Description
STREET                                    138286
APARTMENT                                  94336
RESIDENCE                                  59273
SIDEWALK                                   25917
PARKING LOT / GARAGE (NON RESIDENTIAL)     17413
SMALL RETAIL STORE                         17048
ALLEY                                      11531
RESTAURANT                                 11317
DEPARTMENT STORE                            9860
OTHER (SPECIFY)                             7790
COMMERCIAL / BUSINESS OFFICE                7326
VEHICLE NON-COMMERCIAL                      7103
RESIDENCE - PORCH / HALLWAY                 5933
GAS STATION                                 5932
RESIDENCE - YARD (FRONT / BACK)             5097
Name: count, dtype: int64

In [25]:
# FBI Code
print("Unique FBI Codes:", df_cleaned['FBI Code'].nunique())
print("\nFBI Code Distribution:")
print(df_cleaned['FBI Code'].value_counts())

Unique FBI Codes: 26

FBI Code Distribution:
FBI Code
06     114862
08B     72091
14      55257
07      45845
08A     37063
26      35273
11      27932
03      18849
15      15709
04B     15524
04A     14910
05      14315
18      11468
02       3445
17       3175
24       3101
10       3048
20       1262
01A      1168
09        945
16        455
22        370
13        111
12         69
19         35
01B         8
Name: count, dtype: int64

In [26]:
# Check Arrest and Domestic columns
print("Arrest Distribution:")
print(df_cleaned['Arrest'].value_counts())
print(f"Arrest Rate: {(df_cleaned['Arrest'].sum() / len(df_cleaned) * 100):.2f}%")

print("\nDomestic Distribution:")
print(df_cleaned['Domestic'].value_counts())
print(f"Domestic Crime Rate: {(df_cleaned['Domestic'].sum() / len(df_cleaned) * 100):.2f}%")

Arrest Distribution:
Arrest
False    429273
True      67017
Name: count, dtype: int64
Arrest Rate: 13.50%

Domestic Distribution:
Domestic
False    405809
True      90481
Name: count, dtype: int64
Domestic Crime Rate: 18.23%

In [27]:
# Check Year column
print("Year Distribution:")
print(df_cleaned['Year'].value_counts().sort_index())

# Validate Year matches extracted year from Date
df_cleaned['Year_from_Date'] = df_cleaned['Date'].dt.year
year_mismatch = df_cleaned[df_cleaned['Year'] != df_cleaned['Year_from_Date']]

print(f"\nYear mismatches: {len(year_mismatch)}")
if len(year_mismatch) > 0:
    print("Sample mismatches:")
    print(year_mismatch[['Date', 'Year', 'Year_from_Date']].head())
else:
    print("✓ All Year values match Date column")

# Drop temporary column
df_cleaned = df_cleaned.drop('Year_from_Date', axis=1)

Year Distribution:
Year
2023    195363
2024    257526
2025     43401
Name: count, dtype: int64

Year mismatches: 0
✓ All Year values match Date column

In [28]:

# Check District, Ward, Community Area ranges
print("District range:", df_cleaned['District'].min(), "to", df_cleaned['District'].max())
print("Number of unique Districts:", df_cleaned['District'].nunique())

print("\nWard range:", df_cleaned['Ward'].min(), "to", df_cleaned['Ward'].max())
print("Number of unique Wards:", df_cleaned['Ward'].nunique())

print("\nCommunity Area range:", df_cleaned['Community Area'].min(), "to", df_cleaned['Community Area'].max())
print("Number of unique Community Areas:", df_cleaned['Community Area'].nunique())

District range: 1 to 31
Number of unique Districts: 23

Ward range: 1.0 to 50.0
Number of unique Wards: 50

Community Area range: 1.0 to 77.0
Number of unique Community Areas: 77

In [29]:
# Chicago approximate boundaries
# Latitude: ~41.64 to 42.02
# Longitude: ~-87.94 to -87.52

lat_min, lat_max = 41.6, 42.1
lon_min, lon_max = -88.0, -87.5

print("Checking coordinates are within Chicago bounds...")
print(f"Latitude range: {df_cleaned['Latitude'].min():.6f} to {df_cleaned['Latitude'].max():.6f}")
print(f"Longitude range: {df_cleaned['Longitude'].min():.6f} to {df_cleaned['Longitude'].max():.6f}")

# Find outliers
outlier_coords = df_cleaned[
    (df_cleaned['Latitude'] < lat_min) | (df_cleaned['Latitude'] > lat_max) |
    (df_cleaned['Longitude'] < lon_min) | (df_cleaned['Longitude'] > lon_max)
]

print(f"\nCoordinate outliers: {len(outlier_coords)}")
if len(outlier_coords) > 0:
    print("\nSample outliers:")
    print(outlier_coords[['Block', 'Latitude', 'Longitude', 'Primary Type']].head())
else:
    print("✓ All coordinates within Chicago bounds")

Checking coordinates are within Chicago bounds...
Latitude range: 41.644590 to 42.022549
Longitude range: -87.939733 to -87.524531

Coordinate outliers: 0
✓ All coordinates within Chicago bounds

In [30]:
# Check if Updated On is after Date (should be)
future_updates = df_cleaned[df_cleaned['Updated On'] < df_cleaned['Date']]

print(f"Records where 'Updated On' is before 'Date': {len(future_updates)}")
if len(future_updates) > 0:
    print("\nSample:")
    print(future_updates[['Case Number', 'Date', 'Updated On']].head())
else:
    print("✓ All update dates are logical")

Records where 'Updated On' is before 'Date': 0
✓ All update dates are logical

In [31]:
# Check for invalid hour values (should be 0-23)
invalid_hours = df_cleaned[(df_cleaned['Hour'] < 0) | (df_cleaned['Hour'] > 23)]

print(f"Invalid hour values: {len(invalid_hours)}")
if len(invalid_hours) == 0:
    print("✓ All hours are valid (0-23)")

# Distribution by hour
print("\nCrime distribution by hour:")
print(df_cleaned['Hour'].value_counts().sort_index())

Invalid hour values: 0
✓ All hours are valid (0-23)

Crime distribution by hour:
Hour
0     34532
1     16752
2     14852
3     12899
4     10543
5      9174
6      9631
7     12498
8     17036
9     20486
10    20999
11    21654
12    28070
13    22212
14    23551
15    26909
16    26487
17    26803
18    26401
19    25495
20    24648
21    22768
22    21930
23    19960
Name: count, dtype: int64

In [32]:
# Convert Ward and Community Area to integers (they're currently float)
df_cleaned['Ward'] = df_cleaned['Ward'].astype('int32')
df_cleaned['Community Area'] = df_cleaned['Community Area'].astype('int32')

# Convert smaller integer columns to save memory
df_cleaned['Beat'] = df_cleaned['Beat'].astype('int16')
df_cleaned['District'] = df_cleaned['District'].astype('int8')
df_cleaned['Year'] = df_cleaned['Year'].astype('int16')
df_cleaned['Month'] = df_cleaned['Month'].astype('int8')
df_cleaned['Day'] = df_cleaned['Day'].astype('int8')
df_cleaned['Hour'] = df_cleaned['Hour'].astype('int8')
df_cleaned['DayOfWeek'] = df_cleaned['DayOfWeek'].astype('int8')

print("✓ Optimized data types for memory efficiency")

✓ Optimized data types for memory efficiency

In [33]:
# Memory comparison
memory_mb = df_cleaned.memory_usage(deep=True).sum() / 1024**2
print(f"Current memory usage: {memory_mb:.2f} MB")
print(f"\nMemory by column:")
mem_by_col = df_cleaned.memory_usage(deep=True).sort_values(ascending=False)
print(mem_by_col.head(10))

Current memory usage: 299.21 MB

Memory by column:
Location                38599779
Block                   33501852
Description             32760918
Location Description    30211498
Primary Type            29575543
Case Number             28288527
DayName                 27859751
IUCR                    26303370
FBI Code                25451554
Date                     3970320
dtype: int64

In [34]:
print("="*60)
print("CLEANED DATASET SUMMARY")
print("="*60)
print(f"Total Rows: {len(df_cleaned):,}")
print(f"Total Columns: {len(df_cleaned.columns)}")
print(f"Memory Usage: {df_cleaned.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
print(f"\nDate Range: {df_cleaned['Date'].min()} to {df_cleaned['Date'].max()}")
print(f"\nMissing Values: {df_cleaned.isnull().sum().sum()}")
print(f"\nData Types:")
print(df_cleaned.dtypes.value_counts())

============================================================
CLEANED DATASET SUMMARY
============================================================
Total Rows: 496,290
Total Columns: 27
Memory Usage: 299.21 MB

Date Range: 2023-04-09 07:45:00 to 2025-03-15 10:00:00

Missing Values: 0

Data Types:
object            9
int8              5
float64           4
datetime64[ns]    2
int16             2
bool              2
int32             2
int64             1
Name: count, dtype: int64

In [35]:
# Preview cleaned data
print("\nCleaned Dataset Preview:")
df_cleaned.head()

Cleaned Dataset Preview:

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Month,Day,Hour,DayOfWeek,DayName
0,13812411,JJ226219,2025-03-15 10:00:00,027XX S KOSTNER AVE,0820,THEFT,$500 AND UNDER,VEHICLE NON-COMMERCIAL,False,False,1031,10,22,30,06,1147501.0,1885494.0,2025,2026-03-14 15:41:39,41.841752,-87.734216,"(41.841752071, -87.734215686)",3,15,10,5,Saturday
1,13776074,JJ182219,2025-03-15 10:00:00,024XX W MONTROSE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1911,19,47,5,14,1158860.0,1929140.0,2025,2026-03-14 15:41:39,41.961295,-87.691333,"(41.961295335, -87.691332906)",3,15,10,5,Saturday
2,13775931,JJ182192,2025-03-15 10:00:00,062XX N WINTHROP AVE,0470,PUBLIC PEACE VIOLATION,RECKLESS CONDUCT,RESIDENCE,False,False,2433,24,48,77,24,1167725.0,1941624.0,2025,2026-03-14 15:41:39,41.995365,-87.658379,"(41.995364897, -87.658378839)",3,15,10,5,Saturday
3,13775974,JJ182226,2025-03-15 10:00:00,050XX S BLACKSTONE AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,SCHOOL - PRIVATE GROUNDS,False,False,222,2,4,39,14,1186774.0,1871922.0,2025,2026-03-14 15:41:39,41.803667,-87.590528,"(41.803667488, -87.590528166)",3,15,10,5,Saturday
4,13776897,JJ183396,2025-03-15 10:00:00,105XX S CORLISS AVE,0810,THEFT,OVER $500,STREET,False,False,512,5,9,50,06,1183450.0,1835023.0,2025,2026-03-14 15:41:39,41.702491,-87.603866,"(41.702490996, -87.603866153)",3,15,10,5,Saturday

In [ ]:
import pandas as pd
import numpy as np

# Data quality assessment summary
print("="*70)
print("Final check")
print("="*70)

print(f"\nDATASET OVERVIEW:")
print(f"  - Total Records: {len(df_cleaned):,}")
print(f"  - Total Columns: {len(df_cleaned.columns)}")
print(f"  - Memory Usage: {df_cleaned.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
print(f"  - Date Range: {df_cleaned['Date'].min().date()} to {df_cleaned['Date'].max().date()}")

print(f"\n DATA QUALITY:")
print(f"  - Missing Values: {df_cleaned.isnull().sum().sum()} (0%)")
print(f"  - Duplicate Rows: 0")
print(f"  - Invalid Coordinates: 0")

print(f"\nKEY STATISTICS:")
print(f"  - Unique Crime Types: {df_cleaned['Primary Type'].nunique()}")
print(f"  - Unique Locations: {df_cleaned['Location Description'].nunique()}")
print(f"  - Districts Covered: {df_cleaned['District'].nunique()}")
print(f"  - Wards Covered: {df_cleaned['Ward'].nunique()}")
print(f"  - Arrest Rate: {(df_cleaned['Arrest'].sum() / len(df_cleaned) * 100):.2f}%")
print(f"  - Domestic Crime Rate: {(df_cleaned['Domestic'].sum() / len(df_cleaned) * 100):.2f}%")

======================================================================
Final check
======================================================================

DATASET OVERVIEW:

NameError: name 'df_cleaned' is not defined

In [ ]:
# List all columns with their data types
print("\n COLUMN DETAILS:")
print("="*70)
col_info = pd.DataFrame({
    'Column': df_cleaned.columns,
    'Type': df_cleaned.dtypes.values,
    'Non-Null': df_cleaned.count().values,
    'Unique': [df_cleaned[col].nunique() for col in df_cleaned.columns]
})
print(col_info.to_string(index=False))

📋 COLUMN DETAILS:
======================================================================
              Column           Type  Non-Null  Unique
                  ID          int64    496290  496290
         Case Number         object    496290  496239
                Date datetime64[ns]    496290  243975
               Block         object    496290   32467
                IUCR         object    496290     351
        Primary Type         object    496290      31
         Description         object    496290     329
Location Description         object    496290     140
              Arrest           bool    496290       2
            Domestic           bool    496290       2
                Beat          int16    496290     275
            District           int8    496290      23
                Ward          int32    496290      50
      Community Area          int32    496290      77
            FBI Code         object    496290      26
        X Coordinate        float64    496290   58568
        Y Coordinate        float64    496290   88988
                Year          int16    496290       3
          Updated On datetime64[ns]    496290    1443
            Latitude        float64    496290  193144
           Longitude        float64    496290  193112
            Location         object    496290  193204
               Month           int8    496290      12
                 Day           int8    496290      31
                Hour           int8    496290      24
           DayOfWeek           int8    496290       7
             DayName         object    496290       7

In [ ]:
print("\n TOP 10 CRIME TYPES:")
top_crimes = df_cleaned['Primary Type'].value_counts().head(10)
for i, (crime, count) in enumerate(top_crimes.items(), 1):
    pct = (count / len(df_cleaned)) * 100
    print(f"{i:2d}. {crime:30s} - {count:6,} ({pct:5.2f}%)")

🔍 TOP 10 CRIME TYPES:
 1. THEFT                          - 113,837 (22.94%)
 2. BATTERY                        - 86,813 (17.49%)
 3. CRIMINAL DAMAGE                - 55,257 (11.13%)
 4. MOTOR VEHICLE THEFT            - 45,845 ( 9.24%)
 5. ASSAULT                        - 44,272 ( 8.92%)
 6. OTHER OFFENSE                  - 31,881 ( 6.42%)
 7. DECEPTIVE PRACTICE             - 31,168 ( 6.28%)
 8. ROBBERY                        - 18,849 ( 3.80%)
 9. BURGLARY                       - 15,340 ( 3.09%)
10. WEAPONS VIOLATION              - 15,283 ( 3.08%)

In [40]:
print("\n📍 TOP 10 CRIME LOCATIONS:")
top_locations = df_cleaned['Location Description'].value_counts().head(10)
for i, (loc, count) in enumerate(top_locations.items(), 1):
    pct = (count / len(df_cleaned)) * 100
    print(f"{i:2d}. {loc:30s} - {count:6,} ({pct:5.2f}%)")

📍 TOP 10 CRIME LOCATIONS:
 1. STREET                         - 138,286 (27.86%)
 2. APARTMENT                      - 94,336 (19.01%)
 3. RESIDENCE                      - 59,273 (11.94%)
 4. SIDEWALK                       - 25,917 ( 5.22%)
 5. PARKING LOT / GARAGE (NON RESIDENTIAL) - 17,413 ( 3.51%)
 6. SMALL RETAIL STORE             - 17,048 ( 3.44%)
 7. ALLEY                          - 11,531 ( 2.32%)
 8. RESTAURANT                     - 11,317 ( 2.28%)
 9. DEPARTMENT STORE               -  9,860 ( 1.99%)
10. OTHER (SPECIFY)                -  7,790 ( 1.57%)

In [ ]:
print("\n CRIMES BY YEAR:")
year_counts = df_cleaned['Year'].value_counts().sort_index()
for year, count in year_counts.items():
    print(f"  {year}: {count:,}")

📅 CRIMES BY YEAR:
  2023: 195,363
  2024: 257,526
  2025: 43,401

In [ ]:
print("\n CRIMES BY HOUR OF DAY:")
hour_counts = df_cleaned['Hour'].value_counts().sort_index()
print("\nPeak Hours:")
print(hour_counts.nlargest(5))
print("\nLowest Hours:")
print(hour_counts.nsmallest(5))

⏰ CRIMES BY HOUR OF DAY:

Peak Hours:
Hour
0     34532
12    28070
15    26909
17    26803
16    26487
Name: count, dtype: int64

Lowest Hours:
Hour
5     9174
6     9631
4    10543
7    12498
3    12899
Name: count, dtype: int64

In [ ]:
print("\n CRIMES BY DAY OF WEEK:")
day_counts = df_cleaned['DayName'].value_counts()
# Order by day of week
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
for day in day_order:
    if day in day_counts.index:
        count = day_counts[day]
        pct = (count / len(df_cleaned)) * 100
        print(f"  {day:10s}: {count:6,} ({pct:5.2f}%)")

📆 CRIMES BY DAY OF WEEK:
  Monday    : 71,351 (14.38%)
  Tuesday   : 68,269 (13.76%)
  Wednesday : 70,354 (14.18%)
  Thursday  : 70,019 (14.11%)
  Friday    : 72,848 (14.68%)
  Saturday  : 72,216 (14.55%)
  Sunday    : 71,233 (14.35%)

In [ ]:
print("\n TOP 10 DISTRICTS BY CRIME COUNT:")
district_counts = df_cleaned['District'].value_counts().head(10)
for district, count in district_counts.items():
    pct = (count / len(df_cleaned)) * 100
    print(f"  District {district:2d}: {count:6,} ({pct:5.2f}%)")

🗺️ TOP 10 DISTRICTS BY CRIME COUNT:
  District  8: 32,654 ( 6.58%)
  District 12: 30,322 ( 6.11%)
  District  6: 28,902 ( 5.82%)
  District  1: 28,060 ( 5.65%)
  District  4: 27,025 ( 5.45%)
  District 11: 26,838 ( 5.41%)
  District 19: 26,834 ( 5.41%)
  District 25: 25,966 ( 5.23%)
  District 18: 25,574 ( 5.15%)
  District  2: 25,543 ( 5.15%)

In [45]:
# Save to CSV
output_file = 'chicago_crime_cleaned.csv'
df_cleaned.to_csv(output_file, index=False)
print(f"\n💾 SAVED: {output_file}")
print(f"   File size: {pd.read_csv(output_file).memory_usage(deep=True).sum() / 1024**2:.2f} MB")

💾 SAVED: chicago_crime_cleaned.csv
   File size: 378.25 MB

In [ ]:
# Data dictionary
data_dict = {
    'Column': df_cleaned.columns,
    'Description': [
        'Unique identifier for the record',
        'Case number assigned to the crime',
        'Date and time when the incident occurred',
        'Partially redacted address of the crime',
        'Illinois Uniform Crime Reporting code',
        'Primary description of the crime',
        'Detailed description of the crime',
        'Description of the location where crime occurred',
        'Whether an arrest was made',
        'Whether the crime was domestic-related',
        'Police beat where crime occurred',
        'Police district where crime occurred',
        'City ward where crime occurred',
        'Community area where crime occurred',
        'FBI crime classification code',
        'X coordinate (Illinois State Plane)',
        'Y coordinate (Illinois State Plane)',
        'Year the crime occurred',
        'Date the record was last updated',
        'Latitude coordinate',
        'Longitude coordinate',
        'Location in (latitude, longitude) format',
        'Month extracted from Date',
        'Day of month extracted from Date',
        'Hour of day extracted from Date',
        'Day of week (0=Monday, 6=Sunday)',
        'Name of the day (Monday, Tuesday, etc.)'
    ],
    'Type': df_cleaned.dtypes.values
}

dict_df = pd.DataFrame(data_dict)
dict_df.to_csv('data_dictionary.csv', index=False)
print("\n Data dictionary saved: data_dictionary.csv")
print(dict_df.to_string(index=False))

📖 Data dictionary saved: data_dictionary.csv
              Column                                      Description           Type
                  ID                 Unique identifier for the record          int64
         Case Number                Case number assigned to the crime         object
                Date         Date and time when the incident occurred datetime64[ns]
               Block          Partially redacted address of the crime         object
                IUCR            Illinois Uniform Crime Reporting code         object
        Primary Type                 Primary description of the crime         object
         Description                Detailed description of the crime         object
Location Description Description of the location where crime occurred         object
              Arrest                       Whether an arrest was made           bool
            Domestic           Whether the crime was domestic-related           bool
                Beat                 Police beat where crime occurred          int16
            District             Police district where crime occurred           int8
                Ward                   City ward where crime occurred          int32
      Community Area              Community area where crime occurred          int32
            FBI Code                    FBI crime classification code         object
        X Coordinate              X coordinate (Illinois State Plane)        float64
        Y Coordinate              Y coordinate (Illinois State Plane)        float64
                Year                          Year the crime occurred          int16
          Updated On                 Date the record was last updated datetime64[ns]
            Latitude                              Latitude coordinate        float64
           Longitude                             Longitude coordinate        float64
            Location         Location in (latitude, longitude) format         object
               Month                        Month extracted from Date           int8
                 Day                 Day of month extracted from Date           int8
                Hour                  Hour of day extracted from Date           int8
           DayOfWeek                 Day of week (0=Monday, 6=Sunday)           int8
             DayName          Name of the day (Monday, Tuesday, etc.)         object